# input = your command

commands:
  # Hour
  - commmand:
    input:  Que horas são
    entity: time
    action: getTime
  - commmand:
    input:  Me digas as horas.
    entity: time
    action: getTime
  - commmand:
    input:  Eu quero saber as horas.
    entity: time
    action: getTime
  # Date
  - commmand:
    input:  Qual é O dia de hoje
    entity: time
    action: getDate
  - commmand:
    input:  Data atual.
    entity: time
    action: getDate
    - commmand:
    input:  Que dia é hoje
    entity: time
    action: getDate
  # Weather
  - commmand:
    input:  Previsão do tempo
    entity: weather
    action: getWeather
  - commmand:
    input:  Como está o clima
    entity: weather
    action: getWeather
  # Open
  - commmand:
    input:  Abrir o Chrome
    entity: open
    action: chrome
  - commmand:
    input:  Abra o Chrome
    entity: open
    action: chrome
  - commmand:
    input:  Chrome
    entity: open
    action: chrome
  - commmand:
    input:  Abrir o Google Chrome
    entity: open
    action: chrome
  - commmand:
    input:  Abra o bloco de notas
    entity: open
    action: notepad
  - commmand:
    input:  bloco de notas
    entity: open
    action: notepad
  - commmand:
    input:  Abrir o bloco de notas
    entity: open
    action: notepad